exp_name: "yelp_gcn_node"
random_seed: 42
L: 1
k: 6
Budget: 8
alpha: 1.0
beta: 1.0
gamma: 1.0
max_masks: 4
m: 6
model_name: "gcn1"
hidden_dim: 64
data_name: "Yelp"
data_root: "./datasets"
num_target_nodes: 50
num_epochs: 20
learning_rate: 0.01
weight_decay: 0.0005
batch_size: 128
